Day 131 — NumPy Mini Practice


np.array()
np.zeros()
np.ones()
np.full()

In [ ]:
import numpy as np
l1=[1,2,3,4,5]
A=np.array(l1)
print("Array ==>\n",A)

Array ==>
 [1 2 3 4 5]


In [4]:
print("Zero array ==>\n",np.zeros([3,4]))

Zero array ==>
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
print("Full array ==>\n",np.ones([3,4]))

Full array ==>
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
print("Full array ==>\n",np.full([4,4],28))

Full array ==>
 [[28 28 28 28]
 [28 28 28 28]
 [28 28 28 28]
 [28 28 28 28]]


Task 2 — Special Arrays

np.eye()
np.arange()
np.linspace()

In [12]:
print("Identity array ==>\n",np.eye(6))

Identity array ==>
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [19]:
print("Arange ==>\n",np.arange(0,100,5))

Arange ==>
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [22]:
print("linspace ==>\n",np.linspace(0,100,5))

linspace ==>
 [  0.  25.  50.  75. 100.]


Task 3 — Shape Manipulation

reshape()
flatten()

In [23]:
l3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Reshape  ==>\n",l3.reshape(3,3))

Reshape  ==>
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print("flatten  ==>\n",l3.flatten())

flatten  ==>
 [1 2 3 4 5 6 7 8 9]


Task 4 — Random Numbers

np.random.randint()
np.random.rand()

In [26]:
print("Random. randint ==>\n",np.random.randint(0,100,50))

Random. randint ==>
 [43 37 79 74 97 71 68 91 54 82 76 27  9 34 39 10 17 56 82 28 28 12 70 74
 87 20  1 57 27  8 71 49 14 79 93 48 50 81 31 68 48 68  6 41 75 97 35 62
 69 78]


In [33]:
print("Random. randint ==>\n",np.random.rand(8))

Random. randint ==>
 [0.27432725 0.8356761  0.34651785 0.60752326 0.15963138 0.81433975
 0.64889601 0.45235584]


Task 5 — Array Operations

max()
min()
mean()
sum()

In [34]:
A3=np.array([1,2,3,4,5,6])
print("Max value ==>\n",A3.max())

Max value ==>
 6


In [38]:
print("Min value ==>\n",A3.min())

Min value ==>
 1


In [39]:
print("Mean value ==>\n",A3.mean())

Mean value ==>
 3.5


In [40]:
print("sum value ==>\n",A3.sum())

sum value ==>
 21


Task 6 — Indexing/Slicing

first row
last column
middle values

In [47]:
A4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("First row  ==>\n",A4[0:1,0:4])

First row  ==>
 [[1 2 3]]


In [46]:
print("last row  ==>\n",A4[0:4,2:3])

last row  ==>
 [[3]
 [6]
 [9]]


In [48]:
print("Mid value  ==>\n",A4[1,1])

Mid value  ==>
 5


Bonus Mini Challenge 

values > 50
transpose
diagonal elements
average value

In [51]:
matrix_5x5=np.random.randint(0,100,(5,5))
print(matrix_5x5)

[[13 46 60 79 82]
 [26 22 31 87 21]
 [89 99 77 93 60]
 [12 50 87 61  3]
 [93 97 11 92 64]]


In [ ]:
print("vlues>50 ==>\n",matrix_5x5>50)

vlues>50 ==>
 [[False False  True  True  True]
 [False False False  True False]
 [ True  True  True  True  True]
 [False False  True  True False]
 [ True  True False  True  True]]


In [53]:
print("Transpose ==>\n",matrix_5x5.T)

Transpose ==>
 [[13 26 89 12 93]
 [46 22 99 50 97]
 [60 31 77 87 11]
 [79 87 93 61 92]
 [82 21 60  3 64]]


In [55]:
print("Dignoal elements ==>\n",matrix_5x5.diagonal())

Dignoal elements ==>
 [13 22 77 61 64]


In [56]:
print("Mean value ==>\n",matrix_5x5.mean())

Mean value ==>
 58.2
